application: cssiproject
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /intouch\.css
  static_files: static/intouch.css
  upload: static/intouch\.css

- url: /home\.css
  static_files: static/home.css
  upload: static/home\.css

- url: /navigation\.js
  static_files: static/navigation.js
  upload: static/navigation\.js

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
